[package]
name = "generate-model-distance"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
csv = "1.2"
image = "0.25"
deepface = { path = "..", features = ["yunet", "deepid", "facenet512", "dlib-recognition"] }
burn = { version = "0.19", features = ["ndarray"] }
